# Generated by Django 4.2.5 on 2023-09-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='artists/images/')),
                ('birthname', models.CharField(max_length=100)),
                ('stagename', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'tblartists',
            },
        ),
    ]
