# Generated by Django 4.2.5 on 2023-09-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='birthday',
            new_name='birthdate',
        ),
        migrations.AlterField(
            model_name='artist',
            name='img',
            field=models.FileField(upload_to=''),
        ),
    ]
